# Generated by Django 4.0.2 on 2022-03-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pet_photo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
