# Generated by Django 4.0.2 on 2022-03-27 23:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_photo',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
